### ISSUE TITLE
InvalidArgumentError

### ISSUE THREAD

**Issue by lucyboll** [GuangyuZheng/art-transfer#2]
hello, we get InvalidArgumentError when we test on pos_tagging and ner, the error information is listed as follow:

`Traceback (most recent call last):
  
File "test_art_model.py", line 70, in <module>
    py = model.predict([twx, tx], batch_size=128, verbose=1)

File "/home/qizhang/.conda/envs/art/lib/python3.6/site-packages/keras/engine/training.py", line 1169, in predict     steps=steps)

File "/home/qizhang/.conda/envs/art/lib/python3.6/site-packages/keras/engine/training_arrays.py", line 294, in predict_loop    batch_outs = f(ins_batch)

File "/home/qizhang/.conda/envs/art/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)

File "/home/qizhang/.conda/envs/art/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call  fetched = self._callable_fn(*array_vals)

File "/home/qizhang/.conda/envs/art/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1382, in __call__run_metadata_ptr)

File "/home/qizhang/.conda/envs/art/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__c_api.TF_GetCode(self.status.status))

tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[85,6] = 90 is not in [0, 90)
	 
[[Node: left_char_embed/embedding_1/embedding_lookup = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@left_char_embed/dropout_2/cond/Switch_1"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](embedding_1/embeddings/read, left_char_embed/Reshape, left_char_embed/embedding_1/embedding_lookup/axis)]]`

It seems like resulting from the dimension unequal problem.
How to fix it?

**Comment by GuangyuZheng** [comment]
What is the version of your keras and tensorflow? I have tried to reproduce the reported error and found out it can work under keras==2.2.4 and tensorflow-gpu==1.10.1.

**Comment by lucyboll** [comment]
I found the reason, I just need to use GPU to run the program.
But the obtained accuracy is very low, is there any problem about the pre-trained model? 
Or I need to re-train the model and get my own .h5 file to test?

Here is the result:
`2019-06-05 22:00:57.763277: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2019-06-05 22:00:58.061365: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-05 22:00:58.061422: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0 
2019-06-05 22:00:58.061431: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N 
2019-06-05 22:00:58.061697: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10409 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1)
/home/qizhang/.conda/envs/art/lib/python3.6/site-packages/keras_contrib-2.0.8-py3.6.egg/keras_contrib/layers/crf.py:346: UserWarning: CRF.loss_function is deprecated and it might be removed in the future. Please use losses.crf_loss instead.
/home/qizhang/.conda/envs/art/lib/python3.6/site-packages/keras_contrib-2.0.8-py3.6.egg/keras_contrib/layers/crf.py:353: UserWarning: CRF.accuracy is deprecated and it might be removed in the future. Please use metrics.crf_accuracy

84/84 [==============================] - 3s 35ms/step
ptb to twitter 0.1 0.06146281499692686`

**Comment by GuangyuZheng** [comment]
The result is quite weird... 
The pre-trained model works fine in my environment. Here is the result:

For ptb to twitter 0.1:
2019-06-05 22:40:21.892396: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2019-06-05 22:40:22.146521: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-05 22:40:22.146555: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0
2019-06-05 22:40:22.146563: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N
2019-06-05 22:40:22.146812: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11411 MB memory) -> physical GPU (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:01:00.0, compute capability: 5.2)
/home/zhengguangyu/anaconda3/lib/python3.6/site-packages/keras_contrib/layers/crf.py:346: UserWarning: CRF.loss_function is deprecated and it might be removed in the future. Please use losses.crf_loss instead.
  warnings.warn('CRF.loss_function is deprecated '
/home/zhengguangyu/anaconda3/lib/python3.6/site-packages/keras_contrib/layers/crf.py:353: UserWarning: CRF.accuracy is deprecated and it might be removed in the future. Please use metrics.crf_accuracy
  warnings.warn('CRF.accuracy is deprecated and it '
84/84 [==============================] - 2s 21ms/step
ptb to twitter 0.1 0.8543331284572834

For ptb to twitter 0.01:
2019-06-05 22:44:21.184264: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2019-06-05 22:44:21.438188: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-05 22:44:21.438224: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0
2019-06-05 22:44:21.438232: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N
2019-06-05 22:44:21.438507: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11411 MB memory) -> physical GPU (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:01:00.0, compute capability: 5.2)
/home/zhengguangyu/anaconda3/lib/python3.6/site-packages/keras_contrib/layers/crf.py:346: UserWarning: CRF.loss_function is deprecated and it might be removed in the future. Please use losses.crf_loss instead.
  warnings.warn('CRF.loss_function is deprecated '
/home/zhengguangyu/anaconda3/lib/python3.6/site-packages/keras_contrib/layers/crf.py:353: UserWarning: CRF.accuracy is deprecated and it might be removed in the future. Please use metrics.crf_accuracy
  warnings.warn('CRF.accuracy is deprecated and it '
84/84 [==============================] - 2s 21ms/step
ptb to twitter 0.01 0.702519975414874
